apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-java-app
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: my-java-app
  template:
    metadata:
      labels:
        app: my-java-app
    spec:
      containers:
        - name: my-java-app
          image: alexjaballah/my-java-app:1.0  # Replace with your Docker image name and tag
          ports:
            - containerPort: 8080  # Adjust the port based on your application's configuration
